#! /bin/bash
task1() {
    read -p "Please enter the start of the range: " start
    read -p "Please enter the end of the range: " end

    odd_count=0
    even_count=0
    odd_product=1
    even_product=1

    echo "Triangeular numbers withinin the range are [$start, $end]:"
    for (( n=1; ; n++ )); do
        num=$((n * (n + 1) / 2))
        if (( num > end )); then
            break
        fi
        if (( num >= start )); then
            if (( num % 2 == 0 )); then
                echo "$num (even)"
                even_count=$((even_count + 1))
                even_product=$((even_product * num))
            else
                echo "$num (odd)"
                odd_count=$((odd_count + 1))
                odd_product=$((odd_product * num))
            fi
        fi
    done

    echo "Odd triangular numbers: $odd_count"
    echo "Even triangular numbers: $even_count"
    echo "Product of odd triangular numbers: $odd_product"
    echo "Product of even triangular numbers: $even_product"
}
